on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        reporter: 'github-pr-check'
        checkstyle_config: 'checkstyle/2IP90_checks.xml'