name: Checkstyle

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Checkstyle
        run: |
          curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.4/checkstyle-10.12.4-all.jar

      - name: Run Checkstyle and Capture Output
        id: checkstyle
        run: |
          java -jar checkstyle.jar -c checkstyle/2IP90_checks.xml . > checkstyle_report.txt || true
          echo "::set-output name=checkstyle_output::$(cat checkstyle_report.txt)"

      - name: Check for Warnings and Annotate PR
        run: |
          if grep -q "\[WARN\]" checkstyle_report.txt; then
            echo "Checkstyle found warnings."
            cat checkstyle_report.txt | while IFS= read -r line; do
              if [[ "$line" == *"[WARN]"* ]]; then
                file=$(echo "$line" | awk '{print $2}')
                line_number=$(echo "$line" | awk '{print $3}')
                message=$(echo "$line" | sed 's/\[WARN\]//')

                echo "::warning file=${file},line=${line_number}::Checkstyle Warning: ${message}"
              fi
            done
            exit 1
          else
            echo "Checkstyle passed."
          fi

      - name: Check Checkstyle Output
        run: |
          if grep -q "\[WARN\]" checkstyle_report.txt; then
            echo "Checkstyle found warnings."
            exit 1
          else
            echo "Checkstyle passed."
          fi