name: Checkstyle

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Checkstyle
        run: |
          java -jar /path/to/checkstyle.jar -c checkstyle/2IP90_checks.xml src > checkstyle_report.txt

      - name: Check Checkstyle Output
        run: |
          if grep -q "WARNING" checkstyle_report.txt; then
            echo "Checkstyle found warnings."
          else
            echo "Checkstyle passed."
          fi