name: Checkstyle

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Checkstyle
        run: |
          curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.4/checkstyle-10.12.4-all.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c checkstyle/2IP90_checks.xml ./ > checkstyle_report.txt

      - name: Check Checkstyle Output
        run: |
          if grep -q "WARN" checkstyle_report.txt; then
            echo "Checkstyle found warnings."
          else
            echo checkstyle_report.txt
            echo "Checkstyle passed."
          fi